podName: pod-02
name: aadi
favourite:
  food: biryani
  drink: coke
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
  - pineapple

schema_files:
  - db/master-data.js
  - db/app-user.sql
  - db/schema.sql
  - db/master-data.sql
