apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ quote .Values.favorite.drink }}
  food: {{ quote .Values.favorite.food }}
  snack: {{ .Values.favorite.snack | upper | quote }}
  protein_food: {{ .Values.favorite.protein | default "paneer" | quote }}

## wrapped the output in double quotes
##  food: {{ quote .Values.favorite.food }} --- function call style
##  food: {{ .Values.favorite.food | quote }} --- pipelines style