#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: configmap-01
#data:
#  release_Name: {{ .Release.Name | quote }}
#
#
#
#

# first way to add env into a container
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env-01
data:
  username: abc
  password: xyz
  release_Name: {{ .Release.Name | quote }}
