apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-05
data:
  myvalue: "Hello World"
  drink: {{ .Values.favourite.drink | default "tea" | quote }}
  {{ if eq .Values.favourite.drink "coffee" }}
  name: "aadi"
  {{ end }}
  lname: "jai"
  food: {{ .Values.favorite.food | upper | quote }}






# helm install demo .
# here demo is a releaseName so name: demo-configmap