apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  drink: {{ quote .Values.favorite.drink }}
  food: {{ quote .Values.favorite.food }}
  labels:
    name: aadi
    {{ if eq .Values.favorite.drink "coffee" }}
    food: {{ quote .Values.favorite.snack }}
    {{ end }}



