{{ if  .Values.schema.enabled | default "false" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue
spec:
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
      {{- range .Values.schema_files }}
      env:
        - name: SCHEMA_FILE
          value: {{ . | quote }}
      envFrom:
        - configMapRef:
            name: catalogue-schema
      {{- end }}
      restartPolicy: Never
  backoffLimit: 0
  {{ end }}